[extract_coordinates]
prompt = """Return bounding boxes around every $type with caption.
the bounding boxes should be represented as (x_min, y_min, x_max, y_max) of floating point numbers between 0 and 1.

VERY carefully check the image if there are any $type, and extract the coordinates.
DO NOT extract any coordinates of other types other than $type.
"""

[describe_figure]
prompt = """based on the paper, give me the following information about the attached $type
- actual caption of the $type from the paper with the $type number.
- key description of the $type in single sentence.
- specify the section title of the paper that the $type belongs to.
"""

[double_check_figure]
prompt = "does the image contain $type from the paper?"

[double_check_table]
prompt = """the below html was extracted from the paper by AI.
The AI determined it as table, but it actually might not be a table (i.e. pseudo-code, etc.).
check the html carefully, and say whether it comes from the paper or not.
--------------------------------
$table
"""

[extract_essentials]
prompt = """You are a highly skilled AI research assistant tasked with summarizing academic papers for researchers. Your goal is to extract the core information and present it in a clear, concise, and engaging manner.

For the given research paper, please provide the following:
1. Catchy Summary: Condense the paper's main contribution into a single, eye-catching sentence with less than 200 characters. This should be easily understandable and pique the reader's interest.
2. TL;DR:  Provide a comprehensive summary of the paper in 2 paragraphs. TL;DR should be highly readable and accessible to researchers from various backgrounds, even if they are not experts in the specific field. Focus on clarity and avoid technical jargon as much as possible. Explain key concepts, methods, and findings in a way that is easy to grasp. The first paragraphs shows the background and issues while the second paragraph highlights the paper's method and contributions to address the issues. Each paragraph should be written in 500 characters. 
3. Key Takeaways:  Extract 3 key takeaways that readers should remember from the paper. These should be the most important and impactful findings or contributions.
4. Importance to Researchers:  Explain why this paper is important for researchers in 500 characters. Highlight the potential impact of the research, its relevance to current research trends, and any new avenues it opens for further investigation.

Remember to:
- Avoid redundancy: Ensure that the information provided in each is unique and does not overlap excessively. (i.e. if you already mentioned the project name from the TL;DR, do not mention it again in the other sections)
- Focus on the main idea: Prioritize the core contributions and findings of the paper, ensuring that readers can grasp the main idea effectively.
- Maintain a professional and objective tone: Present the information in a neutral and unbiased manner.
- Wrap text with **bold** in 'TL;DR' and 'Importance to Researchers' sections if it has to be highlighted.
"""

[extract_affiliation]
prompt = """Extract a single affiliation of the main author from the paper.

Some of the known affiliations are listed below. 
If this paper's affiliation is not listed, suggest new affiliation with not too much length. 
Otherwise, return the exact affiliation name that the paper belongs to from the list below.
The affiliation name should not contain any definite article (i.e. "the", "a", "an").

known affiliations: $known_affiliations
"""

[extract_sections]
prompt = """You are a highly skilled AI research assistant tasked with summarizing academic papers for researchers. Your goal is to extract the core information and present it in a clear, concise, and engaging manner.

For the given research paper, please provide the following:
- title of each section
- start and end page index that each section belongs to.

ignore the following sections
- abstract, any subsections, conclusion, appendix, references, related work
"""

[extract_references]
prompt = """among the citations, find the top 20 most important papers with the following info.
- section number that reference belongs to.
- references from each section with first author's name and title of the referenced paper.
- reason why the reference is picked as the most important in 1 paragraph

the target sections are:
$target_sections
"""

[extract_section_details]
prompt = """for the section $section_info, analyze and extract the following information. Think deep and careful, and show me some valuable insights.

- summary in a single sentence.
- keypoints that readers should pay attention to in about 500 characters.
- details expanding the summary. This should be written in 2 paragraphs in 1500 characters total.

It is important not to refer the contents from other sections too much. The purpose is to understand the target section solely and deeply as much as possible.
Also, Wrap important text with **bold**
"""