[extract_coordinates]
prompt = """Extract the coordinates (x_min, y_min, x_max, y_max) of all figures and charts with caption in the given image. 

This shouldn't be best effort, rather strict and thorough.
Ensure that the coordinates should cover the entire region including caption. 
IGNORE math formula, text-only region, and tables. <- These shouldn't be included.

The coordinates should be represented as floating point numbers between 0 and 1, relative to the image size. 
If no figures are found, return an empty array."""

[describe_figure]
prompt = """based on the paper, give me the following information about the attached $type
- caption of the $type from the paper
- detailed description of the $type in single paragraph
- specify the section title of the paper that the $type belongs to.
"""

[double_check_figure]
prompt = "does the image contain $type?"

[extract_essentials]
prompt = """extract and generate the following information from the given paper.
- dense TL;DR of the paper in single paragraph
- 3 takeaways from the paper
- why the paper is important to researchers within 2000 characters
"""

[extract_sections]
prompt = """extract the following information from the given paper.
- title of each section
- start and end page index that each section belongs to.

ignore the following sections
- abstract, subsections, conclusion, appendix, references
"""

[extract_references]
prompt = """among the citations, find the top 20 most important papers with the following info.
- section number that reference belongs to.
- references from each section with first author's name and title of the referenced paper.
- reason why the reference is picked as the most important in 1 paragraph

the target sections are:
$target_sections
"""

[extract_section_details]
prompt = """for the section $section_info, analyze and extract the following information. Think deep and careful, and show me some valuable insights.

- summary in a single paragraph.
- keypoints that readers should pay attention to. if possible, include some numbers for highlighting.
- details expanding the summary in markdown. This should be written in more than 3 paragraphs.
- two pros and two cons about the contents.

It is important not to refer the contents from other sections too much. The purpose is to understand the target section solely and deeply as much as possible.
"""